# Generated by Django 4.0.3 on 2022-03-23 13:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='employee_id')),
                ('first_name', models.CharField(max_length=32)),
                ('second_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('position', models.CharField(max_length=32)),
                ('employment_date', models.DateTimeField()),
                ('monthly_salary', models.IntegerField(default=0)),
                ('paid_salary', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('lead_id', models.UUIDField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
    ]
