# Generated by Django 4.0.3 on 2022-03-24 13:36

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='ФИО')),
                ('position', models.CharField(max_length=32, verbose_name='Должность')),
                ('employment_date', models.DateTimeField(verbose_name='Дата приема на работу')),
                ('monthly_salary', models.IntegerField(default=0, verbose_name='Заработная плата')),
                ('paid_salary', models.IntegerField(default=0, verbose_name='Всего выплачено')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Сотрудник')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='employees.relation', verbose_name='Руководитель')),
            ],
            options={
                'verbose_name_plural': 'Отношения',
                'db_table': 'relations',
            },
        ),
    ]
